%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% compute_paired_ks_tests.m
%
% Compute two-sample Kolmogorov-Smirnov test statistics and p-values from
% an paired-roadmap evaluation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear;
clc;

%% Input data

data_file = fullfile('data', ...
    '1paired_baseline_N2000_lambda_02_safety_08_trials_30.mat');

if ~isfile(data_file)
    error('Paired-roadmap results file not found: %s', data_file);
end

saved_data = load(data_file, 'paired_results');

if ~isfield(saved_data, 'paired_results')
    error('The selected MAT file does not contain paired_results.');
end

results = saved_data.paired_results;

required_variables = { ...
    'marker_off_success', ...
    'marker_on_success', ...
    'marker_off_travel', ...
    'marker_on_travel', ...
    'marker_off_terminal_uncertainty', ...
    'marker_on_terminal_uncertainty', ...
    'marker_off_total_cost', ...
    'marker_on_total_cost'};

missing_variables = setdiff(required_variables, ...
    results.Properties.VariableNames);

if ~isempty(missing_variables)
    error('Missing paired_results variables: %s', ...
        strjoin(missing_variables, ', '));
end

%% Retain complete, finite roadmap pairs

complete_pair = results.marker_off_success & results.marker_on_success;

travel_pair = complete_pair & ...
    isfinite(results.marker_off_travel) & ...
    isfinite(results.marker_on_travel);

uncertainty_pair = complete_pair & ...
    isfinite(results.marker_off_terminal_uncertainty) & ...
    isfinite(results.marker_on_terminal_uncertainty);

cost_pair = complete_pair & ...
    isfinite(results.marker_off_total_cost) & ...
    isfinite(results.marker_on_total_cost);

%% Two-sample Kolmogorov-Smirnov tests

alpha = 0.05;

[travel_h, travel_p, travel_ks] = kstest2( ...
    results.marker_off_travel(travel_pair), ...
    results.marker_on_travel(travel_pair), ...
    'Alpha', alpha);

[uncertainty_h, uncertainty_p, uncertainty_ks] = kstest2( ...
    results.marker_off_terminal_uncertainty(uncertainty_pair), ...
    results.marker_on_terminal_uncertainty(uncertainty_pair), ...
    'Alpha', alpha);

[cost_h, cost_p, cost_ks] = kstest2( ...
    results.marker_off_total_cost(cost_pair), ...
    results.marker_on_total_cost(cost_pair), ...
    'Alpha', alpha);

%% Summary table

metric = ["Travel distance"; "Terminal uncertainty"; "Total objective"];
number_of_pairs = [sum(travel_pair); sum(uncertainty_pair); sum(cost_pair)];

mean_without_marker = [ ...
    mean(results.marker_off_travel(travel_pair)); ...
    mean(results.marker_off_terminal_uncertainty(uncertainty_pair)); ...
    mean(results.marker_off_total_cost(cost_pair))];

mean_with_marker = [ ...
    mean(results.marker_on_travel(travel_pair)); ...
    mean(results.marker_on_terminal_uncertainty(uncertainty_pair)); ...
    mean(results.marker_on_total_cost(cost_pair))];

ks_statistic = [travel_ks; uncertainty_ks; cost_ks];
p_value = [travel_p; uncertainty_p; cost_p];
significant_at_005 = logical([travel_h; uncertainty_h; cost_h]);

ks_results = table(metric, number_of_pairs, mean_without_marker, ...
    mean_with_marker, ks_statistic, p_value, significant_at_005);

fprintf('Two-sample Kolmogorov-Smirnov tests (alpha = %.2f)\n', alpha);
fprintf('Data file: %s\n\n', data_file);
disp(ks_results);

fprintf(['Interpretation: significant_at_005 is true when the two-sample ', ...
    'KS test rejects equal distributions at p < 0.05. The sample means ', ...
    'show the direction of each change.\n']);
