close all
% This function plots the enviroment and the optimal path
% You need to run this codes after loading mat file or right after you
% finished run the simulation

% Load the PRM result generated by main.m.
% Change this name when main.m is run with different parameters.
result_file = 'data/main_baseline_with_marker_N2000_lambda_02_safety_08';
load(result_file)

% start the figure
figure
hold on

axis equal
xlim([bound(1).x(1) bound(1).x(2)]);
ylim([bound(2).x(1) bound(2).x(2)]);
hold on

% colors used in the figure
color_b = [0    0.4470    0.7410];
color_p = [0.4940    0.1840    0.5560];
% color used to fill the obstacles
%color_fill = [1, 0, 0]; 
color_fill = [187/255,139/255,172/255];

% goal region patch : green
x_patch = [target(1,1) target(1,2) target(1,2) target(1,1)];
y_patch = [target(2,1) target(2,1) target(2,2) target(2,2)];
goal_patch = patch(x_patch,y_patch, [0.8 1 0.8]);

%% plot obstacles

% Saved polygons
for kk = 1:length(obs_polyshape)
    fill(obs_polyshape(kk).x, obs_polyshape(kk).y, color_fill, ...
        'EdgeColor', 'k', 'LineWidth', 0.5)
end

% Show the marker and sensing radius for marker-present runs.
if exist('marker_enabled','var') && marker_enabled
    theta_marker = linspace(0,2*pi);
    plot(marker.x(1) + marker.sensing_radius*cos(theta_marker), ...
        marker.x(2) + marker.sensing_radius*sin(theta_marker), '--', ...
        'Color', color_p, 'LineWidth', 1)
    plot(marker.x(1), marker.x(2), 'p', 'Color', color_p, ...
        'MarkerFaceColor', color_p, 'MarkerSize', 10)
end

%% plot optimal path and confidence ellipses
theta_grid = linspace(0,2*pi);
marker_has_been_sensed = false;

% Plot ellipses connecting two nodes
for jj = 1:length(saver(end).path)-1
    x0 = node(saver(end).path(jj)).x;
    xF = node(saver(end).path(jj+1)).x;
    P0 = node(saver(end).path(jj)).P;
    edge_distance = norm(x0-xF);
    move_vec = (xF - x0)/(num_props+1);

    % If this edge first enters the marker range, propagate to the sensing
    % point, apply its EKF update, then propagate the remaining distance.
    edge_senses_marker = false;
    if exist('marker_enabled','var') && marker_enabled && ~marker_has_been_sensed
        [edge_senses_marker, marker_fraction] = marker_encounter(x0, xF, marker);
        if edge_senses_marker
            P_before_marker = P0 + R*(marker_fraction*edge_distance);
            P_after_marker = ekf_update_covariance(P_before_marker, marker.H, marker.R);
        end
    end

    for zz = 1:num_props+1
        prop(zz).x = x0 + move_vec*zz;
        edge_fraction = zz/(num_props+1);

        if edge_senses_marker && edge_fraction > marker_fraction
            prop(zz).P = P_after_marker + ...
                R*((edge_fraction-marker_fraction)*edge_distance);
        else
            prop(zz).P = P0 + R*(edge_fraction*edge_distance);
        end

        [prop(zz).ra,prop(zz).rb,prop(zz).ang,prop(zz).ellipse_rect] = error_ellipse(prop(zz).x,prop(zz).P,chi);
        ellipse_x_r  = prop(zz).ra*cos( theta_grid );
        ellipse_y_r  = prop(zz).rb*sin( theta_grid );
        Rot = [ cos(prop(zz).ang) sin(prop(zz).ang); -sin(prop(zz).ang) cos(prop(zz).ang) ];
        r_ellipse = [ellipse_x_r;ellipse_y_r]' * Rot;
        plot(r_ellipse(:,1) + prop(zz).x(1),r_ellipse(:,2) + prop(zz).x(2), 'color', color_b)
        hold on;
    end

    if edge_senses_marker
        marker_has_been_sensed = true;
    end
end
%%
% Plot initial node with red dots
start_handle = plot(node(1).x(1),node(1).x(2),'ro','MarkerSize',6,'MarkerFaceColor','r');
%%
% Plot each node
trajectory_handle = plot(nan, nan, 'k-', 'LineWidth', 2);
for jj = 1:length(saver(end).path)-1
    plot([node(saver(end).path(jj)).x(1) node(saver(end).path(jj+1)).x(1)],[node(saver(end).path(jj)).x(2) node(saver(end).path(jj+1)).x(2)],'k','LineWidth',2);
    plot(node(saver(end).path(jj)).x(1),node(saver(end).path(jj)).x(2),'ko','MarkerSize',4,'MarkerFaceColor','k');
    ellipse_x_r  = node(saver(end).path(jj)).ra*cos( theta_grid );
    ellipse_y_r  = node(saver(end).path(jj)).rb*sin( theta_grid );
    Rot = [ cos(node(saver(end).path(jj)).ang) sin(node(saver(end).path(jj)).ang); -sin(node(saver(end).path(jj)).ang) cos(node(saver(end).path(jj)).ang) ];
    r_ellipse = [ellipse_x_r;ellipse_y_r]' * Rot;
    plot(r_ellipse(:,1) + node(saver(end).path(jj)).x(1),r_ellipse(:,2) + node(saver(end).path(jj)).x(2),'k-','LineWidth',1.5)
end


%%
% Plot boundary of region and target region
rectangle('Position',[bound(1).x(1), bound(2).x(1), bound(1).x(2) - bound(1).x(1),  bound(2).x(2)- bound(2).x(1)],'EdgeColor',color_fill,'LineWidth',1.2)
rectangle('Position',[target(1,1) target(2,1) target(1,2)-target(1,1) target(2,2)-target(2,1)],'EdgeColor',[0 0.5 0],'LineWidth',1.5)

xlabel("Location X [m]")
ylabel("Location Y [m]")

% Change for different plots
title('Baseline example with marker')

% For multi
set(gca, 'FontName', 'Arial', 'FontSize', 12)
ylim([bound(2).x(1) bound(2).x(2)]);
set(gca,'color','white');
grid on
set(gca,'LineWidth',1)
ax = gca;
ax.LineWidth = 1;


fig_f = gcf;
% The size and position of figure
% For multi
fig_f.Position = [650 100 550 512];
xticks([0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1])

% Legend handles
covariance_handle = plot(nan, nan, '-', 'Color', color_b, 'LineWidth', 1.5);
legend_handles = [trajectory_handle, covariance_handle];
legend_labels = {'Trajectory', 'Covariance'};

if exist('marker_enabled','var') && marker_enabled
    marker_range_handle = plot(nan, nan, '--', 'Color', color_p, 'LineWidth', 1);
    marker_handle = plot(nan, nan, 'p', 'Color', color_p, ...
        'MarkerFaceColor', color_p, 'MarkerSize', 10);
    legend_handles = [legend_handles, marker_range_handle, marker_handle];
    legend_labels = [legend_labels, {'Marker range', 'Marker'}];
end

legend_handles = [legend_handles, start_handle, goal_patch];
legend_labels = [legend_labels, {'Start', 'Goal'}];
legend(legend_handles, legend_labels, 'Location', 'northwest', 'FontSize', 12)

% Save the figure beside its source data using the same base file name.
[result_folder, result_name] = fileparts(result_file);
exportgraphics(fig_f, fullfile(result_folder, [result_name, '.png']), ...
    'Resolution', 300)

